services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./internal/db/migrations:/migrations:ro
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE}?x-migrations-table=schema_migrations"
      , "up"
    ]
    env_file: .env   

  app:
    build: .
    container_name: todo-app
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    command: ["api", "-a", ":8080"]
    ports:
      - "8080:8080"

volumes:
  db_data:
