services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: todo-app
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    command: ["api", "-a", ":8080"]
    ports:
      - "8080:8080"

volumes:
  db_data:
